### ISSUE TITLE
Add Install Date to agents-list

### ISSUE THREAD

**Issue by bradyschulman** [jumolinas/tetrationcli#7]
headers = ['UUID', 'Host Name', 'Agent Type', 'Last Check-in', 'Install Date', 'Version', 'Scopes']
            data_list = [[x['uuid'],
                        x['host_name'],
                        x['agent_type'],
                        time.strftime('%Y-%m-%d %H:%M:%S',
                            time.localtime(x['last_config_fetch_at'])),
                        time.strftime('%Y-%m-%d %H:%M:%S',
                            time.localtime(x['created_at'])),
                        x['current_sw_version'],
                        ','.join(set([y['vrf'] for y in x['interfaces']])) ]
                                                for x in data['results'] ]

**Comment by jumolinas** [comment]
Master has the new feature, working on some features to push to official

**Comment by jumolinas** [comment]
Done
